#sudo: required

language: java
jdk: openjdk11

#services: docker

install:
  - mvn clean install -DskipTests

script:
  - mvn test
  - mkdir build
  - cp Dockerfile build/Dockerfile
  - cp docker-compose.yml build/docker-compose.yml
  - cp target/spring-docker-demo.jar build/spring-docker-demo.jar
  - ls build
  - ls


deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  zip_file: "build/*"
  #must be the region the Elastic Beanstalk application is running on
  region: "ap-south-1"
  #name of the application that you set up in Elastic beanstalk
  app: "spring-docker-demo"
  #Elastic Beanstalk environment the application will be deployed to.
  env: "Springdockerdemo-env"
  #The Elastic beanstalk has its own folder in S3 that contains all projects.
  bucket_name: "elasticbeanstalk-ap-south-1-058827412234"
  #Location within Bucket to upload app to.
  bucket_path: "spring-docker-demo"
  #This will tell Travis to what branch to triggers build.
  on:
    branch: master
    tags: false
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"


