#sudo: required

language: java
jdk: openjdk11

#services: docker

install:
  - mvn clean install -DskipTests

script:
  - mvn test


deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  #file: "Dockerfile"
  zip_file:
    - target/spring-docker-demo.jar
  region: "ap-south-1"
  app: "spring-docker-demo"
  env: "Springdockerdemo-env"
  bucket_name: "elasticbeanstalk-ap-south-1-058827412234"
  #Location within Bucket to upload app to.
  bucket_path: "spring-docker-demo"
  on:
    branch: master
    tags: false
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"