sudo: required

language: java
jdk: openjdk11

services: docker

install:
  - mvn clean install -DskipTests

script:
  - mvn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "spring-docker-demo"
  env: "DockerEnv"
  bucket_name: "elasticbeanstalk-us-east-1-058827412234"
  bucket_path: "spring-docker-demo"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY