language: java

jdk: openjdk11

install:
  - mvn clean install -DskipTests

script:
  - mvn test

before_deploy:
  - git add target/spring-docker-demo.jar
  - git commit -m "added jar file"

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  #must be the region the Elastic Beanstalk application is running on
  region: "ap-south-1"
  #name of the application that you set up in Elastic beanstalk
  app: "spring-docker-demo"
  #Elastic Beanstalk environment the application will be deployed to.
  env: "SpringDockerDemo-env"
  #The Elastic beanstalk has its own folder in S3 that contains all projects.
  bucket_name: "elasticbeanstalk-ap-south-1-058827412234"
  #Location within Bucket to upload app to.
  bucket_path: "spring-docker-demo"
  #This will tell Travis to what branch to triggers build.
  on:
    branch: master
    tags: false
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"

after_deploy:
  - git rm -r target


