sudo: required

services: docker

install:
  - mvn clean install -DskipTests

script:
  - mvn test

before_deploy:
  - docker-compose build

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  #name of the application that you set up in Elastic beanstalk
  app: "spring-docker-demo"
  #Elastic Beanstalk environment the application will be deployed to.
  env: "Springdockerdemo-env"
  #The Elastic beanstalk has its own folder in S3 that contains all projects.
  bucket_name: "elasticbeanstalk-ap-south-1-058827412234"
  #Location within Bucket to upload app to.
  bucket_path: "spring-docker-demo"
  #This will tell Travis to what branch to triggers build.
  on:
    branch: master
    tags: false
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"


