sudo: required

language: java
jdk: openjdk11

services: docker

install:
  - mvn clean install -DskipTests

script:
  - mvn test

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  zip_file: '/home/travis/build/ankitsharmaa049/spring-docker-demo/target/spring-docker-demo.jar'
  region: "ap-south-1"
  app: "spring-docker-demo"
  env: "Springdockerdemo-env"
  bucket_name: "elasticbeanstalk-ap-south-1-058827412234"
  bucket_path: "spring-docker-demo"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"