sudo: required

language: java
jdk: openjdk11

services: docker

before_install:
  - echo "$AWS_ACCESS_KEY"
  - echo "$AWS_SECRET_KEY"

install:
  - mvn clean install -DskipTests

script:
  - mvn test

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "spring-docker-demo"
  env: "DockerEnv"
  bucket_name: "elasticbeanstalk-us-east-1-058827412234"
  bucket_path: "spring-docker-demo"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"